server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  messages:
    basename: messages
  security:
    user:
      name: username
      password: passw0rd

menagement:
  endpoints:
    web:
      exposure:
        include: "*"
